### ISSUE TITLE
Problem with 'extract' module in testris

### ISSUE THREAD

**Issue by adam-royles** [LearnProgramming/learntris#45] opened 2015-05-29 16:18 UTC
Dear community, 

I'm new to this so please forgive me if I can't see the wood for the trees. When I compile and run the 'testris.py' file I get the following error relating to a module. The output is pasted below. 

```
Traceback (most recent call last):
  File "F:\Programming\Python\learntris\PythonApplication1\PythonApplication1\PythonApplication1.py", line 159, in main
    run_tests(cmdline, use_shell)
  File "F:\Programming\Python\learntris\PythonApplication1\PythonApplication1\PythonApplication1.py", line 124, in run_tests
    for i, test in enumerate(extract.tests()):
NameError: name 'extract' is not defined
```

Would someone be so kind as to give me a hint at where I'm going wrong? 

I'm using Visual studio 2015 RC to build the testris code and I'll probably continue using python to build my version of 'learntris'

Many thanks

**Comment by raylu** [comment] 2015-05-29 18:43
It looks like you've modified the testris.py code and moved it 3 directories deep and called it PythonApplication1.py...

You should build an app completely independently of testtris.py and then run the unmodified testris.py on your code.

**Comment by adam-royles** [comment] 2015-05-29 21:59
Currently I am starting a new project in vs, and it has the default name of pythonpplication1. I then copy and paste the testris.py code into there and run it. Beforehand I've started a new Python project that is completely empty and called it learntris. I have then modified the testris.py code to look for the learntris.py file. 

I'm guessing from your response I need to run something from the command line and not modify the code at all? Is it important the the testris and learntris files are in the same folder? What is the literal meaning of "the default path is ./learntris"??

Thanks

**Comment by raylu** [comment] 2015-05-30 00:26
The testris.py code runs tests against some program and the expected output in testplan.org. There's no tetris code in there so I have no idea why you're copying it.

`.` is the current directory, `/` is a path separator, so `./learntris` is a file called `learntris` in the current directory. This is a file you create. On windows, you will want to pass it `./learntris.exe` or similar.

**Comment by adam-royles** [comment] 2015-05-30 12:21
ok, am I getting any closer?? I've abandoned Visual studio and just used IDLE to create a blank program called learntris.py.

When I try and run in command prompt I get the following message. 

C:\learntris> python.exe testris.py learntris.py
Traceback (most recent call last):
  File "testris.py", line 22, in <module>
    import extract
ImportError: No module named 'extract'

If I change the learntris.py to an exe file I still get the same error. I know this is probably painfully simple to your guys but I can't interpret the instructions any other way!!

Thanks

**Comment by darkf** [comment] 2015-05-30 14:06
@adam-royles You don't have the full learntris source in `C:\learntris`... Re-clone the repo there.

**Comment by darkf** [comment] 2015-05-30 14:07
This is also not a bug, so closing. If you need help, feel free to join us on IRC at `#lpmc` or `#learnprogramming` at `irc.freenode.net`

**Closed by darkf** 2015-05-30 14:07 UTC
